prd:
  catalog_name: mlops_prd
  schema_name: corretco
  cleaned_table_name: us_accidents_cleaned
acc:
  catalog_name: mlops_acc
  schema_name: corretco
  cleaned_table_name: us_accidents_cleaned
dev:
  catalog_name: mlops_dev
  schema_name: corretco
  cleaned_table_name: us_accidents_cleaned

experiment_name: /Shared/us-accidents-basic
model_names:
  model1: us_accidents_model
  model2: us_accidents_model_and_feature

endpoint_names:
  endpoint1: us_accidents_model_serving
  endpoint2: us_accidents_model_and_feature_serving

parameters:
  n_estimators: [10, 50, 100]
  max_features: ['sqrt']
  cv: 5
  n_jobs: 8
  scoring: f1_macro

num_features:
  - Timezone_US/Eastern
  - Timezone_US/Mountain
  - Timezone_US/Pacific
  - Weekday_1
  - Weekday_2
  - Weekday_3
  - Weekday_4
  - Weekday_5
  - Weekday_6
  - Station
  - Stop
  - Traffic_Signal
  - Severity_4
  - Rd
  - St
  - Dr
  - Ave
  - Blvd
  - I-
  - Astronomical_Twilight_Night

cat_features:
  - Start_Lat
  - Start_Lng
  - Pressure_bc

target: Severity_4
