prd:
  catalog_name: mlops_prd
  schema_name: house_prices
acc:
  catalog_name: mlops_acc
  schema_name: house_prices
dev:
  catalog_name: mlops_dev
  schema_name: house_prices

num_features:

cat_features: