prd:
  catalog_name: mlops_prd
  schema_name: corretco
  cleaned_table_name: us_accidents_cleaned
acc:
  catalog_name: mlops_acc
  schema_name: corretco
  cleaned_table_name: us_accidents_cleaned
dev:
  catalog_name: mlops_dev
  schema_name: corretco
  cleaned_table_name: us_accidents_cleaned

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - Timezone_US/Eastern
  - Timezone_US/Mountain
  - Timezone_US/Pacific
  - Weekday_1
  - Weekday_2
  - Weekday_3
  - Weekday_4
  - Weekday_5
  - Weekday_6
  - Station
  - Stop
  - Traffic_Signal
  - Severity_4
  - Rd
  - St
  - Dr
  - Ave
  - Blvd
  - I-
  - Astronomical_Twilight_Night

cat_features:
  - Start_Lat
  - Start_Lng
  - Pressure_bc

target: Severity_4
