prd:
  catalog_name: mlops_prd
  schema_name: corretco
  cleaned_table_name: us_accidents_cleaned
acc:
  catalog_name: mlops_acc
  schema_name: corretco
  cleaned_table_name: us_accidents_cleaned
dev:
  catalog_name: mlops_dev
  schema_name: corretco
  cleaned_table_name: us_accidents_cleaned

experiment_name: /Shared/us-accidents-basic
model_names:
  model1: us_accidents_model
  model2: us_accidents_model_and_feature

endpoint_names:
  endpoint1: us_accidents_model_serving
  endpoint2: us_accidents_model_and_feature_serving

parameters:
  n_estimators: [10, 50, 100]
  max_features: ['sqrt']
  cv: 5
  n_jobs: 8
  scoring: f1_macro

num_features:
  - Weekday
  - Station
  - Stop
  - Traffic_Signal

cat_features:
  - Timezone
  - Street
  - Start_Lat
  - Start_Lng
  - Pressure_in
  - Astronomical_Twilight

target: Severity
